Fixed typo.
Rev: server/perl/bin/perlrun:1.3

diff --git a/server/perl/bin/perlrun b/server/perl/bin/perlrun
--- a/server/perl/bin/perlrun
+++ b/server/perl/bin/perlrun
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# $Id: perlrun,v 1.2 2000/08/17 15:17:46 leif Exp $
+# $Id: perlrun,v 1.3 2001/06/15 07:57:16 leif Exp $
 
 DIR="`dirname $0`"
 if [ ! -f "$DIR/perlhelper" ] ; then
@@ -16,5 +16,5 @@ do
      exec $X/perl "$DIR/perlhelper" $*
   fi
 done
-echo >&2 "$0 $$: unable to local Perl interpreter"
+echo >&2 "$0 $$: unable to locate Perl interpreter"
 exit 1
