Mega commit: Indent text files with spaces only.
Fixes [REP-1024].

diff --git a/server/tools/ntroxen/bump_ntstart_version b/server/tools/ntroxen/bump_ntstart_version
--- a/server/tools/ntroxen/bump_ntstart_version
+++ b/server/tools/ntroxen/bump_ntstart_version
@@ -18,8 +18,8 @@ fail()
 version_fixup()
 {
     if [ -f ntstart/ntstart.cpp -a -f version.h ]; then :; else
-	echo "Invalid current directory for bumping ntstart."
-	fail
+        echo "Invalid current directory for bumping ntstart."
+        fail
     fi
 
     echo "Bumping ntstart version..."
@@ -46,10 +46,10 @@ version_fixup()
 
     if [ "x$nocvs" = "x" ]
     then
-	echo git commit -m "Version bumped to $version.$newbuild by distmaker." version.h
-	git commit -m "Version bumped to $version.$newbuild by distmaker." version.h \
-	|| fail
-	git push || fail
+        echo git commit -m "Version bumped to $version.$newbuild by distmaker." version.h
+        git commit -m "Version bumped to $version.$newbuild by distmaker." version.h \
+        || fail
+        git push || fail
     fi
 
     echo "$version.$newbuild" > VERSION
@@ -60,9 +60,9 @@ version_fixup()
     if [ "x$nocvs" = "x" ]
     then
         echo Tagging...
-	echo git tag "ntstart_$VERSION"
+        echo git tag "ntstart_$VERSION"
         git tag "ntstart_$VERSION" || fail
-	git push origin "refs/tags/ntstart_$VERSION" || fail
+        git push origin "refs/tags/ntstart_$VERSION" || fail
     else
         echo No tagging!
     fi
